### ISSUE TITLE
Does not work on ubuntu 19.10

### ISSUE THREAD

**Issue by njdaniel** [njdaniel/Pyfa#1]
## Bug Report

gui error:
=============================================================
pyfa v2.34.0
EVE Data Version: None (None)

OS version: Linux-5.3.0-7642-generic-x86_64-with-Ubuntu-19.10-eoan
Python version: 3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008]
wxPython version: 4.1.1 (wxWidgets 3.1.5)
SQLAlchemy version: 1.4.10
Logbook version: 1.5.3
Requests version: 2.25.1
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/home/nick/dev/github.com/pyfa-org/PyfaDEV/gui/mainFrame.py", line 62, in <module>
    from gui.updateDialog import UpdateDialog
  File "/home/nick/dev/github.com/pyfa-org/PyfaDEV/gui/updateDialog.py", line 25, in <module>
    import wx.html2
  File "/home/nick/dev/github.com/pyfa-org/PyfaDEV/PyfaEnv/lib/python3.7/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkitgtk-1.0.so.0: cannot open shared object file: No such file or directory

### Detailed steps to reproduce:
git clone
cd
python -m vent PyfaEnv
source PyfaEnv/bin/activate
pip install -r requirements.txt
*error wxPython

### Release or development git branch? Please note the release version or commit hash:
master

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Ubuntu 19.10

**Comment by njdaniel** [comment]
pip install was failing

pip install -U  -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
    
 pip now works but  gui error is now showing

**Comment by njdaniel** [comment]
pip install --upgrade pip
update requirements.txt for wxPython to 4.1.1

success pip install

**Comment by njdaniel** [comment]
Success
